### ISSUE TITLE
Trigger fs sync if something changed remote

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-desktop#125]

**Comment by julianseeger** [comment]
Remote DM was damaged
```
Exception in thread "Thread-10" java.lang.ArrayIndexOutOfBoundsException: 32
    at org.spongycastle.crypto.modes.GCMBlockCipher.processBytes(GCMBlockCipher.java:290)
    at de.qabel.core.crypto.CryptoUtils.decryptFileAuthenticatedSymmetricAndValidateTag(CryptoUtils.java:201)
    at de.qabel.desktop.storage.FolderNavigation.reloadMetadata(FolderNavigation.java:49)
    at de.qabel.desktop.storage.cache.CachedBoxNavigation.refresh(CachedBoxNavigation.java:181)
```

**Comment by julianseeger** [comment]
Closed by @thechauffeur.
