### ISSUE TITLE
Logged exception when creating an account

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-desktop#416]
```
Exception in thread "Thread-9" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-9
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.stage.Window.setShowing(Window.java:921)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at de.qabel.desktop.DesktopClientGui.showMainStage(DesktopClientGui.java:118)
	at de.qabel.desktop.DesktopClientGui.lambda$start$0(DesktopClientGui.java:60)
	at de.qabel.desktop.config.RepositoryBasedClientConfig.lambda$setAccount$0(RepositoryBasedClientConfig.java:71)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at de.qabel.desktop.config.RepositoryBasedClientConfig.setAccount(RepositoryBasedClientConfig.java:71)
	at de.qabel.desktop.ui.accounting.login.LoginController.lambda$createBoxAccount$5(LoginController.java:189)
	at java.lang.Thread.run(Thread.java:745)
```

Fresh installation and I created a new account. The application did not crash.

Version: 19b36c7fe9dc2daef703d3cc43a2a47edc324e2b

**Comment by julianseeger** [comment]
Also happens on login. Thats why the desktop clients starts not minimized ...
Solution (DesktopClientGui.java):
```
     config.onSetAccount(account -> {
                initBackgroundServices();
                Platform.runLater(this::showLayoutStage);
            }
        );
```

**Comment by thechauffeur** [comment]
I don't know if this is the only issue regarding the bug that the desktop does not start minimized and I don't know if this should be fixed in the release because I cannot assume bad implications of the fix for this. I moved this to current sprint and in the RC milestone but this may be wrong.

Please discuss. I may then move into an other pipeline and milestone.
