### ISSUE TITLE
ClassNotFoundException with OpenJFX and OpenJDK

### ISSUE THREAD

**Issue by lsfxz** [Qabel/qabel-desktop#420]
New content of the ticket:
Make sure that the client works with OpenJFX and OpenJDK.

--------------------------
As promised: Trying to run qabel-desktop on Arch using OpenJDK 8u102 and OpenJFX 8u76 fails with the following exception:

```
java.lang.ClassNotFoundException: com.sun.deploy.uitoolkit.impl.fx.HostServicesFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.sun.javafx.application.HostServicesDelegate.lambda$getInstance$0(HostServicesDelegate.java:52)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.HostServicesDelegate.getInstance(HostServicesDelegate.java:45)
        at de.qabel.desktop.Kernel.initialize(Kernel.java:85)
        at de.qabel.desktop.DesktopClient.main(DesktopClient.java:24)
Exception in thread "main" java.lang.NullPointerException
        at de.qabel.desktop.Kernel.initialize(Kernel.java:85)
        at de.qabel.desktop.DesktopClient.main(DesktopClient.java:24)
```

This happens with 0.7.0-beta.2-b8, but also if I build it myself from `master`.

Some google usage hints at "javafx.deploy" missing from OpenJFX, which might be the culprit.
( [https://bugs.openjdk.java.net/browse/JDK-8160464](https://bugs.openjdk.java.net/browse/JDK-8160464) )

By the way, my current attempt at a PKGBUILD for Arch can be found in [this gist](https://gist.github.com/lsfxz/b227a325f277cd34bcd832f34b286869).

**Comment by audax** [comment]
We only use this class to run the auto-updater.
`documentLauncher.accept(checker.getDesktopVersion().getDownloadURL());`

**Comment by audax** [comment]
Does the proposed workaround from the JDK bug work for you?
` java -addmods javafx.deploy HostServicesTest `

**Comment by lsfxz** [comment]
I already tried that (probably should have added it in the first place):
```
Unrecognized option: --addmods
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by enkore** [comment]
IIRC all options to `java` are single dash form. Like `java -addmods`.

**Comment by lsfxz** [comment]
No idea how that got there… but with a single dash the only thing that changes is that I get `Unrecognized option: -addmods`

**Comment by audax** [comment]
`java -Djdk.launcher.addmods=javafx.deploy`

**Comment by lsfxz** [comment]
That way java accepts the option without complaining – but, unfortunately, qabel still exits with `java.lang.ClassNotFoundException: com.sun.deploy.uitoolkit.impl.fx.HostServicesFactory`.

**Comment by audax** [comment]
I hate Oracle.

**Comment by enkore** [comment]
![asdf](http://i.imgur.com/ktBbzZ9.jpg)

**Comment by julianseeger** [comment]
ftr.: we can remove the HostServicesDelegate and use the `java.awt.Desktop` to do the same. If that's the only usage of javafx.deploy, we are fine.

**Comment by lsfxz** [comment]
That works. (Well, at least it doesn't crash and I get to the login window – I can't test any further until I'm back home, there's a rather ugly proxy in place here which qabel can't get through)
